server:
  port: 8080

spring:
  mail:
    default-encoding: utf-8
    host: smtp.163.com
    password: HQFZFPBNVJVWZSDJ
    username: liu109976@163.com
  application:
    name: demo

#MQ配置
rocketmq:
  name-server: 10.0.128.138:9876
  producer:
    group: GID_OPG_AMS
#    customized-trace-topic: ams-audit-ready

logging:
  file:
    path: /ams/logs

swagger:
  enable: true
  application-name: ${spring.application.name}
  application-version: 1.0
  application-description: springfox swagger 3.0 Demo
  try-host: http://localhost:${server.port}/swagger-ui/
